### ISSUE TITLE
捉虫

### ISSUE THREAD

**Issue by FairyOwO** [windshadow233/Mahjong-AI#7]
https://github.com/windshadow233/Mahjong-AI/blob/9e27716d180b6b1731d31d7f62600298dc01d8e1/model/models.py#L121
训练reward模型的时候, 可以传入hidden_dims, 修改隐藏层维度, 但GAU层之后的Linear是固定维度, 不支持修改

变更为

```python
nn.Linear(hidden_dims, 10),
```

**Comment by windshadow233** [comment]
感谢指出！
这块是胡乱写的，还没有实现后续的强化学习流程，因此没太注意😇

FairyOwO ***@***.***>于2024年2月27日 周二13:59写道：
