### ISSUE TITLE
吃碰杠的模型不用单独训吗？

### ISSUE THREAD

**Issue by Iriya99** [windshadow233/Mahjong-AI#8]
作者好！天凤的数据格式里面似乎只能表示副露，而不能表示出是哪一种，只训练副露模型实战中会不会出问题呀_(:з」∠)_

**Comment by windshadow233** [comment]
你好～天凤数据格式用整数类型编码副露，和副露种类形成一一对应，具体细节可见[天鳳の牌譜形式を解析する（2）](https://blog.kobalab.net/entry/20170228/1488294993)，故牌谱里的副露已经蕴含副露的类型了，训练时肯定是训练3个副露模型

**Comment by windshadow233** [comment]
我看了一下，是我readme没写清楚，训练副露模型的那条命令有个mode参数，用来指定训练的是啥模型

**Comment by Iriya99** [comment]
好滴好滴，感谢大佬的代码~
